// <auto-generated />
namespace HelpDesk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class EditedTheActivityTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedTheActivityTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201401211915059_EditedTheActivityTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
